name: 'Hello World'
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest, etc.
    steps:
      - uses: actions/checkout@v4
      - name: Echo text
        run: echo "Hello, world!"


